---
# main tasks file for install_ocp_prerequisites role
- name: "[INCLUDE TASK] - Download Python libraries"
  ansible.builtin.import_tasks:
    file: download-python-libraries.yaml

- name: "[INCLUDE TASK] - Download OCP binaries"
  ansible.builtin.import_tasks:
    file: download-ocp-binaries.yaml
  become: true
...
